### ISSUE TITLE
Issue with mixins?

### ISSUE THREAD

**Issue by lSherozl** [DragonsPlusMinecraft/VisualityReforged#7]
[crash-2023-05-05_01.05.24-client.txt](https://github.com/DragonsPlusMinecraft/visuality-forge/files/11404066/crash-2023-05-05_01.05.24-client.txt)

**Comment by lSherozl** [comment]
After some testing with the modpack, I believe one of these mods or more conflict with visuality, as removing the set amount of mods allows me to make a world now with visuality included which I could not do with these mods added, I suspect the mod that is causing issues in this list is most likely aquamirae, cause some of these other mods do seem like they work with visuality
<img width="671" alt="image" src="https://user-images.githubusercontent.com/65663746/236590690-55b265e7-09ac-4b91-a094-334960d7ec49.png">

**Comment by DadoIrie** [comment]
Having similar issue on here during launch which indicates to mixins

Exception in thread "main" java.lang.module.ResolutionException: Modules MixinExtras.beta._6 and debugify export package com.llamalad7.mixinextras to module appleskin
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
 	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
 	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
 	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
 	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.

Disabling Debugify resolves it and Minecraft launches, but I thought this might be interesting. Hope it helps
